baseURL = 'https://spectredxxx.github.io/'
languageCode = 'zh-cn'
title = '曜风'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Theme configuration
[params]
  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection = '*'

  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'
  BookFavicon = '/favicon.jpeg'

  # Custom CSS
  BookCustomCSS = ['/custom.css']

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'base16-snazzy'




[caches]
  [caches.images]
    dir = ':cacheDir/images'